# Generated by Django 2.2.24 on 2022-05-03 08:30

from django.db import migrations
from django.db.models import F
from django.core.exceptions import MultipleObjectsReturned

def owners_flats_relation_autocreator(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all().iterator():
        try:
            flats_owner, created = Owner.objects.get_or_create(owner_name=flat.owner)
            flats_owner.flats_of_owner.add(flat)
        except MultipleObjectsReturned:
            flats_owners = Owner.objects.filter(owner_name=flat.owner)
            for flats_owner in flats_owners:
                flats_owner.flats_of_owner.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20220503_1111'),
    ]

    operations = [
        migrations.RunPython(owners_flats_relation_autocreator)
    ]
